### ISSUE TITLE
InvalidOperationException thrown when using class with generic type constraints

### ISSUE THREAD

**Issue by jasonwoods-7** [Fody/Janitor#11]
Whenever you use Janitor on a class which has a generic type constraint, any use of the methods of the class will throw System.InvalidOperationException: Could not execute the method because either the method itself or the containing type is not fully instantiated.

Here is a small example app which shows the issue.

```c#
  class Foo<T> : IDisposable
    where T : IComparable
  {
    public void Dispose() { }
    private void DisposeManaged() { }
    public void Bar() { }
  }

  public class Program
  {
    static void Main(string[] args)
    {
      using (var foo = new Foo<int>())
        foo.Bar();
    }
  }
```

**Comment by SimonCropp** [comment]
try the new nuget

**Comment by jasonwoods-7** [comment]
Excellent!  Works great!
