### ISSUE TITLE
Readonly field Dispose

### ISSUE THREAD

**Issue by abelevtsov** [Fody/Janitor#127]
Hi,

I am wondering why Janitor can not dispose private readonly fields (which are IDisposable), even if it possible by myself?
 
>  [] Fody/Janitor: Could not add dispose for field '_networkInfo' since it is marked as readonly. Change this field to not be readonly.

Kind regards,
Aleksandr

**Comment by SimonCropp** [comment]
@abelevtsov i remove this restriction. also to be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
