### ISSUE TITLE
Skip weaving of all types in namespace

### ISSUE THREAD

**Issue by timbussmann** [Fody/Janitor#20]
When using source-only packages, the IDisposable implementations of the "external" types can conflict with Janitor. This usually requires adding `[SkipWeaving]` attributes to the code.
* This works when the code is fully copy&pasted or using the "old" nuget source-only style but it requires some effort to go through all affected types. Also it makes the code harder to update, as you have to go though the updated code again an readd all the attributes.
* This doesn't work when using the "new" nuget source-only package style because changes to the source file are only applied to the file in your local nuget cache and won't be applied the projects on different machines.

sadly, it looks like it's not possible to add attributes to namespaces directly. I have a [working spike](https://github.com/timbussmann/Janitor/tree/skip-namespace) which uses assembly-level attributes instead, the usage would look like this:
`[assembly: SkipWeavingNamespace("NamespaceToSkip")]`. 
I'm happy to open a PR if you're interested in this spike.

**Comment by timbussmann** [comment]
ping @SimonCropp

**Comment by SimonCropp** [comment]
happy with a PR
