### ISSUE TITLE
struct with base classes can not be skipped

### ISSUE THREAD

**Issue by f-israel** [Fody/Janitor#28]
Not sure if this is just me or the addin. 

I got an (inner) struct with some unsupported base classes. Can't add [Janitor.SkipWeaving] - which in this case would be the answer - as this is restricted to classes and fields. (BTW: I'm aware that this struct usage is anything but best practice. But it's good working third party code so I don't touch it more than I need.)

Code example - removed the implementations as not needed for demonstration:
```
public class ObservableDictionary<TKey, TValue> :
        IDictionary<TKey, TValue>,
        ICollection<KeyValuePair<TKey, TValue>>,
        IEnumerable<KeyValuePair<TKey, TValue>>,
        IDictionary,
        ICollection,
        IEnumerable,
        ISerializable,
        IDeserializationCallback,
        INotifyCollectionChanged,
        INotifyPropertyChanged
        {
            [Serializable, StructLayout(LayoutKind.Sequential)]
            public struct Enumerator<TKey, TValue> : IEnumerator<KeyValuePair<TKey, TValue>>, IDictionaryEnumerator, IEnumerator
            { 

            }
        }
```

Possible solutions could be to extend the attributes scope to structs or ignore such kind of structs at all.

**Comment by SimonCropp** [comment]
happy to accept a PR that fixes this
